name: Build site on schedule or main branch update

on:
  # push:
  #   branches:
  #     - main
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: '0 5,6 * * *' # cronで定期実行。UTCなので9時間プラスしてあげること

jobs:
  build:
    runs-on: ubuntu-latest # 最新のubuntu環境で下記のジョブを実行
    steps:
      - uses: actions/checkout@v2 # おまじない

      - name: Setup python
        uses: actions/setup-python@v2 # Pythonのセットアップ
        with:
          python-version: "3.8" # Pythonのバージョン指定
          architecture: x64
      - name: Install dependencies # Pythonの依存環境のインストール
        run: | #このような書き方で複数行を一気に実行することができる。
          python -m pip install --upgrade pip
          pip install pandas
          pip install beautifulsoup4
          pip install requests

      - name: Run ranking_detect_korea.py # 韓国ランキング
        run: |
          python ranking_detect_korea.py
      # - name: Run ranking_lv_jpn.py # 日本ランキング
      #   run: |
      #     python ranking_lv_jpn.py
      - name: git setting
        run: |
          git config --global user.email "sokomincontact@gmail.com"
          git config --global user.name "sokomin"
          git config --local user.email "sokomincontact@gmail.com"
          git config --local user.name "sokomin"
          git config pull.rebase false
          git add .
          git diff --exit-code || git commit -m "Add ranking data." -a
          git pull
          git push origin main
