name: Build site on schedule or main branch update

on:
#   push:
#     branches:
#       - main
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: '0 11,12 * * *' # cronで定期実行。UTCなので9時間プラスしてあげること

jobs:
  build:
    runs-on: ubuntu-latest # 最新のubuntu環境で下記のジョブを実行
    steps:
      - uses: actions/checkout@v2 # おまじない
#       - name: Open Docker
#         run: |
#           docker run --rm --cap-add=NET_ADMIN --device=/dev/net/tun --dns=1.1.1.1 --dns=8.8.8.8 --dns=9.9.9.9 -p 8118:8118 tantantanuki/ja-vpngate-proxy
      - name: Setup python
        uses: actions/setup-python@v2 # Pythonのセットアップ
        with:
          python-version: "3.8" # Pythonのバージョン指定
          architecture: x64
      - name: Install dependencies # Pythonの依存環境のインストール
        run: | #このような書き方で複数行を一気に実行することができる。
          python -m pip install --upgrade pip
          pip install pandas
          pip install beautifulsoup4
          pip install requests

      - name: Run ranking_lv_korea.py # 韓国ランキング
        run: |
          python ranking_detect_korea.py
          python ranking_lv_korea.py
      # - name: Run ranking_lv_jpn.py # 日本ランキング
      #   run: |
      #     python ranking_lv_jpn.py
      - name: commit & push
        run: |
          git add -N . # 新規ファイルを含める
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update"
            git push
          fi
